---
title: "Reflection Exercise 3"
author: 
  - Diana Shen
thanks: "Code and data are available at: https://github.com/DianaShen1224/Reflection-exercise-3."
date: today
date-format: long
abstract: "This is a Paper for in-class reflection exercise 3."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
analysis_data<-read.csv("~/Reflection exercise 3/data/analysis_data/analysis_data.csv")
```

# Introduction

You can and should cross-reference sections and sub-sections. We use @citeR, @opendatatoronto and @rohan.

The remainder of this paper is structured as follows. @sec-data....

# Data {#sec-data}

Our data conduct analysis of the location of marriage from 2011 to 2024 in Toronto @fig-location. We can see that city of Toronto has the highest marriage.

```{r}
#| label: fig-location
#| fig-cap: Location of Marriage
#| echo: false
#| message: false
#| warning: false
analysis_data |>
  group_by(year,civic_centre) |>
  summarize(total_marriage_licenses = sum(marriage_licenses))|>
  ggplot(aes(x = year,y=total_marriage_licenses,color=civic_centre)) +
  geom_line() +
  theme_minimal() +
  labs(
    x = "Year", y = "Number of marriage",
    color = "Civic Center"
  ) +
  scale_color_brewer(palette = "Set1")+
  theme(legend.position = "bottom")
```

\newpage

# References
